### ISSUE TITLE
Mission chest empty when it should contain items

### ISSUE THREAD

**Issue by tacotexmex** [thomasrudin-mt/missions#2]
The mission chest is empty when the owner looks in it, even when another player has deposited items to it.

**Comment by tacotexmex** [comment]
But then we lose a whole incentive for players to create transport missions! For example, if I as an established player is doing a large building project in need of certain material, I may use a transport mission to incentivize new players getting this material for me.

Also, since the items put into a missions are ”real” items and not ”pseudo” items (both source and reward are taken from my inventory) it feels like an unbalance that the source items gets purged from the world.

**Comment by thomasrudin** [comment]
Yes, that sounds reasonable, haven't thought about it that way.
I have to rethink the way the mission-chest works but i see even a use-case if i build something myself and need a ton of materials...

**Comment by thomasrudin** [comment]
done, follow-up: #11
